### ISSUE TITLE
Nothing happening when clicking on "Login" after installation

### ISSUE THREAD

**Issue by acclaimuser** [MistyKuu/bitbucket-for-visual-studio#78] opened 2018-08-20 15:26 UTC
Nothing happening when clicking on "Login" after installation this plugin with VS 2017 Enterprise 15.8

I am able to login to my bitbucket without this plugin. this plugin seems to be not working with VS 2017 ?

I am having Resharper installed with my Vs instance, is that something blocking?

please let me know. Thanks.

**Comment by MistyKuu** [comment] 2018-08-21 16:58
Hey,
please send the logs located under %appdata%/gitclientvsextension/logs

**Comment by acclaimuser** [comment] 2018-08-21 17:40
attached the logs.

[logs.txt](https://github.com/MistyKuu/bitbucket-for-visual-studio/files/2307396/logs.txt)

**Comment by MistyKuu** [comment] 2018-08-21 17:51
This is a bug, I'll look into it.

**Comment by freeweaver** [comment] 2018-08-23 18:48
I've been having the same issue since updating to VS 2017 15.8, but it's the same on 15.8.1

[logs.txt](https://github.com/MistyKuu/bitbucket-for-visual-studio/files/2315768/logs.txt)

**Comment by MistyKuu** [comment] 2018-08-23 21:13
Any chance 1.37.91 helps?

**Comment by acclaimuser** [comment] 2018-08-23 21:28
No luck. updated logs are here.
[logs.txt](https://github.com/MistyKuu/bitbucket-for-visual-studio/files/2316252/logs.txt)

**Comment by freeweaver** [comment] 2018-08-24 21:49
Same with, latest logs here.
[logs.txt](https://github.com/MistyKuu/bitbucket-for-visual-studio/files/2319984/logs.txt)

**Comment by eliezeralmeida** [comment] 2018-08-27 12:04
Me too!
[logs.txt](https://github.com/MistyKuu/bitbucket-for-visual-studio/files/2323757/logs.txt)

**Comment by MistyKuu** [comment] 2018-08-27 17:32
Please check 1.37.92. I've upgraded mah apps + changed the way it's imported. Please let me know if it helped.

**Comment by coolraj80** [comment] 2018-08-28 02:43
Hi,
My colleague who's on Windows 7 is able to now see the logon screen and the plugin works fine after he did the update, but i'm on Windows 10, and it's just displaying a frame (transparent) and i can't see anything else.
My Visual Studio version and the plugin versions are exactly the same as my colleague, the only difference I can see is the OS version.
I'm attaching the Log file and screenshot of what I see on my screen.

[BitBucket Plugin Log.txt](https://github.com/MistyKuu/bitbucket-for-visual-studio/files/2326278/BitBucket.Plugin.Log.txt)
![bitbucket screenshot](https://user-images.githubusercontent.com/19592746/44697634-316c9b00-aaaf-11e8-96c0-117d84246fbc.png)

**Comment by BerendWouters** [comment] 2018-08-28 08:26
Sadly enough, 1.37.93 (the latest version on the Marketplace and Extensions) still doesn't work.
[logs.txt](https://github.com/MistyKuu/bitbucket-for-visual-studio/files/2327151/logs.txt)

**Comment by MistyKuu** [comment] 2018-08-28 08:43
Yea it shows different error now:
`---> System.Windows.Markup.XamlParseException: Initialization of 'MahApps.Metro.Controls.ContentControlEx' threw an exception. ---> System.InvalidOperationException: Can only base on a Style with target type that is base type 'ContentControlEx'.`

Any chance one of you guys clone the repo and try to fix this? I can't reproduce it on my side so it's very hard to find an issue.

**Comment by freeweaver** [comment] 2018-08-28 16:00
The latest update works for me, other than there being no visible labels on the login fields. I got back in though.

**Comment by eliezeralmeida** [comment] 2018-08-29 13:13
i have the same problem: https://github.com/MistyKuu/bitbucket-for-visual-studio/issues/78#issuecomment-416432570

My log: [logs.txt](https://github.com/MistyKuu/bitbucket-for-visual-studio/files/2332235/logs.txt)

**Comment by chrno1209** [comment] 2018-08-29 15:10
I have the same problem on VS2017 15.8.1, my log: 
[logs.txt](https://github.com/MistyKuu/bitbucket-for-visual-studio/files/2332679/logs.txt)

**Comment by illuminat281090** [comment] 2018-08-29 20:55
ghost border on top of all windows for me as well, VS 2017 15.8.2, run as admin
![image](https://user-images.githubusercontent.com/24498981/44814810-6e877900-abe6-11e8-9cfe-173cbec50361.png)
![image](https://user-images.githubusercontent.com/24498981/44814923-bdcda980-abe6-11e8-98cb-8d0580df9cde.png)

Exception is follwoing (without inner)
2018-08-29 23:50:13,299 [1] ERROR GitClientVS.VisualStudio.UI.GitClientVSPackage [(null)] - Unhandled Dispatcher GitClientVsExtensions Error
ReactiveUI.UnhandledErrorException: An object implementing IHandleObservableErrors (often a ReactiveCommand or ObservableAsPropertyHelper) has errored, thereby breaking its observable pipeline. To prevent this, ensure the pipeline does not error, or Subscribe to the ThrownExceptions property of the object in question to handle the erroneous case. ---> System.Windows.Markup.XamlParseException: Initialization of 'MahApps.Metro.Controls.ContentControlEx' threw an exception. ---> System.InvalidOperationException: Can only base on a Style with target type that is base type 'ContentControlEx'.
   at System.Windows.Style.Seal()
   at System.Windows.Style.System.Windows.ISealable.Seal()
   at System.Windows.StyleHelper.SealIfSealable(Object value)
   at System.Windows.ResourceDictionary.SealValue(Object value)
   at System.Windows.ResourceDictionary.OnGettingValue(Object key, Object& value, Boolean& canCache)
   at System.Windows.ResourceDictionary.OnGettingValuePrivate(Object key, Object& value, Boolean& canCache)
   at System.Windows.ResourceDictionary.GetValueWithoutLock(Object key, Boolean& canCache)
   at System.Windows.ResourceDictionary.GetValue(Object key, Boolean& canCache)
   at System.Windows.ResourceDictionary.FetchResource(Object resourceKey, Boolean allowDeferredResourceReference, Boolean mustReturnDeferredResourceReference, Boolean canCacheAsThemeResource, Boolean& canCache)
   at System.Windows.SystemResources.LookupResourceInDictionary(ResourceDictionary dictionary, Object key, Boolean allowDeferredResourceReference, Boolean mustReturnDeferredResourceReference, Boolean& canCache)
   at System.Windows.SystemResources.FindDictionaryResource(Object key, Type typeKey, ResourceKey resourceKey, Boolean isTraceEnabled, Boolean allowDeferredResourceReference, Boolean mustReturnDeferredResourceReference, Boolean& canCache)
   at System.Windows.SystemResources.FindResourceInternal(Object key, Boolean allowDeferredResourceReference, Boolean mustReturnDeferredResourceReference)
   at System.Windows.StyleHelper.GetThemeStyle(FrameworkElement fe, FrameworkContentElement fce)
   at System.Windows.FrameworkElement.UpdateThemeStyleProperty()
   at System.Windows.FrameworkElement.OnInitialized(EventArgs e)
   at System.Windows.FrameworkElement.TryFireInitialized()
   at System.Windows.FrameworkElement.EndInit()
   at MS.Internal.Xaml.Runtime.ClrObjectRuntime.InitializationGuard(XamlType xamlType, Object obj, Boolean begin)

**Comment by mzhukovs** [comment] 2018-08-30 10:05
*bump*

**Comment by runealbrigtsen** [comment] 2018-09-03 15:42
Same stacktrace as illuminat281090, but no ghost borders (ie nothing happens when clicking Clone, Create, etc).   

Bitbucket For Visual Studio Version: 1.37.93
Visual Studio Version: 15.8.2 (Professional)
OS: Windows 10, Version 1803 (April 2018 Update), Build 17134.228. 

Would like to help, but don't really know where to start debugging vsix stuff.

**Comment by MistyKuu** [comment] 2018-09-04 17:00
Actually debugging is pretty simple. All you have to do is to configure executable path for your visual studio instance like this: 
My path: C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\\devenv.exe
Arguments: /rootsuffix Exp

Once you do it just start debugging GitClientVS.VisualStudio.UI project.

![image](https://user-images.githubusercontent.com/10333668/45045809-762aa000-b074-11e8-8fa3-f32c12419537.png)

I will try to make one more change, just create base style programatically, I hope it's gonna help.

**Comment by MistyKuu** [comment] 2018-09-04 17:12
Can anyone try to install this version? I can't upload new version because marketplace is temporarily offline.

[GitClientVS.VisualStudio.UI.zip](https://github.com/MistyKuu/bitbucket-for-visual-studio/files/2349532/GitClientVS.VisualStudio.UI.zip)

**Comment by chrno1209** [comment] 2018-09-04 17:34
tested it and didn't work at all, now I can't click on login, or if I click on login link, nothing happens. log attached
[logs.txt](https://github.com/MistyKuu/bitbucket-for-visual-studio/files/2349593/logs.txt)

**Comment by illuminat281090** [comment] 2018-09-05 07:37
the same stack trace as for chrno1209

**Comment by MistyKuu** [comment] 2018-09-05 07:40
I can't really help you guys as I'm shooting in the dark. The project is open source so feel free to clone it and replicate it locally. In the previous posted I explained how to debug it. The issue is in DefaultWindowMetroStyle which is based on default style of MahApps.Metro window. It seems like Metro dlls are not loaded when style is trying to resolve the base type.

**Comment by dirtknap** [comment] 2018-09-05 13:28
If I run the project in debug mode, it works.  I can log in, everything is fine. I have tried uninstalling the extension and reinstall it but it still doesn't work.  I suspect that something is not being packaged up in the extension installer.

**Comment by MistyKuu** [comment] 2018-09-05 15:47
@dirtknap 
Could you do the same using "Release" build?

**Comment by freeweaver** [comment] 2018-09-05 15:51
Is it possible to upload that new version now? Microsoft had a major data center outage yesterday that's been resolved now.

**Comment by MistyKuu** [comment] 2018-09-05 15:55
@freeweaver it doesn't seem like new version fixed the issue but I will upload it anyway

**Comment by VlaTo** [comment] 2018-09-06 06:46
Just updated to the last version available (1.37.94) but still hothing happened when clicking on "Login".
[logs-09-06-2018.txt](https://github.com/MistyKuu/bitbucket-for-visual-studio/files/2355821/logs-09-06-2018.txt)

**Comment by AngelBermudez57** [comment] 2018-09-07 12:37
I there any way to install an older version 1.37.91 was the last working version for me. I keep it on my VS2013 so I can load and create projects. The latest version 1.37.94 is on my  VS 2017 were you can not clone or create.

**Comment by mzhukovs** [comment] 2018-09-10 06:09
Can confirm with latest VS2017 v15.8.3 and latest BitBucket extension v1.37.94 Login button does nothing. Previously, it brought up an empty frame in the middle of the screen that you couldn't get rid of nor do anything with. Now, nothing happens at all.

**Comment by MistyKuu** [comment] 2018-09-10 15:49
Hey Guys,
anyone to keen to test this version? I force MahApps to load on startup. If that doesn't work I'll sign MahApps.Metro assemblies.
[GitClientVS.VisualStudio.UI.zip](https://github.com/MistyKuu/bitbucket-for-visual-studio/files/2367364/GitClientVS.VisualStudio.UI.zip)

**Comment by Ogglas** [comment] 2018-09-11 06:07
@MistyKuu The version you linked worked for me. When I downloaded the official version from marketplace I could not login either.

https://marketplace.visualstudio.com/items?itemName=MistyK.VisualStudioBitbucketExtension#overview

**Comment by MistyKuu** [comment] 2018-09-11 06:17
No worries, I haven't uploaded a new version yet. If that works I'll do that later today, however the thing I did is just workaround but not a proper solution.

**Comment by MistyKuu** [comment] 2018-09-11 17:36
I've just released 1.37.95. Please let me know if it helped.

**Comment by runealbrigtsen** [comment] 2018-09-11 20:43
Yay. Works for me at least. Good job!

**Comment by mzhukovs** [comment] 2018-09-12 08:43
Works!

**Comment by coolraj80** [comment] 2018-09-12 09:07
Works for me too... thank you :+1:

**Comment by MistyKuu** [comment] 2018-09-12 09:13
Thanks guys, I'm closing this issue.

**Closed by MistyKuu** 2018-09-12 09:13 UTC
Labels: bug
