### ISSUE TITLE
Not working in VS2017

### ISSUE THREAD

**Issue by noremorse1** [MistyKuu/bitbucket-for-visual-studio#37] opened 2017-11-14 09:06 UTC
Installed extension v1.37.1 ok in VS 2017 v15.4.3 and I see it in Team Explorer, but when I click on Login absolutely nothing happens. No popup window to login, no error message, nothing at all. I have uninstalled and reinstalled it but same result. Please assist.

This is from the log.

2017-11-13 15:32:15,572 [1] ERROR GitClientVS.VisualStudio.UI.GitClientVSPackage [(null)] - Unhandled Dispatcher GitClientVsExtensions Error
ReactiveUI.UnhandledErrorException: An object implementing IHandleObservableErrors (often a ReactiveCommand or ObservableAsPropertyHelper) has errored, thereby breaking its observable pipeline. To prevent this, ensure the pipeline does not error, or Subscribe to the ThrownExceptions property of the object in question to handle the erroneous case. ---> Microsoft.VisualStudio.Composition.CompositionFailedException: An exception was thrown while initializing part "GitClientVS.UI.Views.LoginDialogView". ---> System.Windows.Markup.XamlParseException: Initialization of 'GitClientVS.UI.Styles.SharedResourceDictionary' threw an exception. ---> System.InvalidOperationException: 'MetroWindow' TargetType does not match type of element 'LoginDialogView'.
   at System.Windows.Style.CheckTargetType(Object element)
   at System.Windows.StyleHelper.UpdateStyleCache(FrameworkElement fe, FrameworkContentElement fce, Style oldStyle, Style newStyle, Style& styleCache)
   at System.Windows.FrameworkElement.OnStyleChanged(DependencyObject d, DependencyPropertyChangedEventArgs e)
   at System.Windows.DependencyObject.OnPropertyChanged(DependencyPropertyChangedEventArgs e)
   at System.Windows.FrameworkElement.OnPropertyChanged(DependencyPropertyChangedEventArgs e)
   at System.Windows.DependencyObject.NotifyPropertyChange(DependencyPropertyChangedEventArgs args)
   at System.Windows.DependencyObject.UpdateEffectiveValue(EntryIndex entryIndex, DependencyProperty dp, PropertyMetadata metadata, EffectiveValueEntry oldEntry, EffectiveValueEntry& newEntry, Boolean coerceWithDeferredReference, Boolean coerceWithCurrentValue, OperationType operationType)
   at System.Windows.DependencyObject.InvalidateProperty(DependencyProperty dp, Boolean preserveCurrentValue)
   at System.Windows.ResourceReferenceExpression.InvalidateExpressionValue(Object sender, EventArgs e)
   at System.Windows.TreeWalkHelper.InvalidateResourceReferences(DependencyObject d, ResourcesChangeInfo info)
   at System.Windows.TreeWalkHelper.OnResourcesChanged(DependencyObject d, ResourcesChangeInfo info, Boolean raiseResourceChangedEvent)
   at System.Windows.TreeWalkHelper.InvalidateOnResourcesChange(FrameworkElement fe, FrameworkContentElement fce, ResourcesChangeInfo info)
   at System.Windows.ResourceDictionary.NotifyOwners(ResourcesChangeInfo info)
   at System.Windows.ResourceDictionary.EndInit()
   at MS.Internal.Xaml.Runtime.ClrObjectRuntime.InitializationGuard(XamlType xamlType, Object obj, Boolean begin)
   --- End of inner exception stack trace ---
   at System.Windows.Markup.WpfXamlLoader.Load(XamlReader xamlReader, IXamlObjectWriterFactory writerFactory, Boolean skipJournaledProperties, Object rootObject, XamlObjectWriterSettings settings, Uri baseUri)
   at System.Windows.Markup.WpfXamlLoader.LoadBaml(XamlReader xamlReader, Boolean skipJournaledProperties, Object rootObject, XamlAccessLevel accessLevel, Uri baseUri)
   at System.Windows.Markup.XamlReader.LoadBaml(Stream stream, ParserContext parserContext, Object parent, Boolean closeStream)
   at System.Windows.Application.LoadComponent(Object component, Uri resourceLocator)
   at GitClientVS.UI.Views.LoginDialogView.InitializeComponent()
   at GitClientVS.UI.Views.LoginDialogView..ctor(ILoginDialogViewModel vm)
   --- End of inner exception stack trace ---
   at Microsoft.VisualStudio.Composition.RuntimeExportProviderFactory.RuntimeExportProvider.RuntimePartLifecycleTracker.CreateValue()
   at Microsoft.VisualStudio.Composition.ExportProvider.PartLifecycleTracker.Create()
   at Microsoft.VisualStudio.Composition.ExportProvider.PartLifecycleTracker.MoveNext(PartLifecycleState nextState)
   at Microsoft.VisualStudio.Composition.ExportProvider.PartLifecycleTracker.GetValueReadyToExpose()
   at Microsoft.VisualStudio.Composition.RuntimeExportProviderFactory.RuntimeExportProvider.<>c__DisplayClass13_0.<CreateExportFactory>b__0()
   at Microsoft.VisualStudio.Composition.ExportProvider.<>c__DisplayClass54_0.<CreateExportFactory>b__0()
   at Microsoft.VisualStudio.Composition.DelegateServices.<>c__DisplayClass2_0`1.<As>b__0()
   at System.ComponentModel.Composition.ExportFactory`1.CreateExport()
   at GitClientVS.Infrastructure.ViewModels.ConnectSectionViewModel.<InitializeCommands>b__45_0()
   at ReactiveUI.ReactiveCommand.<>c__DisplayClass1_0`1.<Create>b__1(IObserver`1 observer)
   at System.Reactive.AnonymousObservable`1.SubscribeCore(IObserver`1 observer)
   at System.Reactive.ObservableBase`1.Subscribe(IObserver`1 observer)
   --- End of inner exception stack trace ---
   at ReactiveUI.RxApp.<>c__DisplayClass0_0.<.cctor>b__2()
   at System.Reactive.Concurrency.Scheduler.Invoke(IScheduler scheduler, Action action)
   at System.Reactive.Concurrency.DispatcherScheduler.<>c__DisplayClass1`1.<Schedule>b__0()
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by MistyKuu** [comment] 2017-11-15 16:18
Hm, is there a way I can reproduce it? Could you maybe download sources, build, install with vsix and debug on your end? It's really hard to say, it sounds like a conflict between different versions of MahApps.

**Comment by vambola** [comment] 2017-11-28 15:22
Experiencing the same issue on Win7 Visual Studio 2017 15.4.5. Any ideas how to fix this?

**Comment by dwilkie1** [comment] 2017-11-28 19:17
I have the same issue. Win Server 2012 R2 VS 2017 15.4.0

**Comment by MistyKuu** [comment] 2017-11-28 20:20
Guys this project is Open-source mainly because I wanted some people to be able to contribute in it. I really can't reproduce this issue with the latest Visual Studio. Could you please download sources and try to debug it? Project should build out of the box.

**Comment by dwilkie1** [comment] 2017-11-29 15:06
Got it to work by building the solution and installing from bin\debug\GitClientVS.VisualStudio.UI.vsix. Not sure why this worked but would be happy to provide more info if someone could point me in the right direction.

**Comment by papyr** [comment] 2018-01-19 06:30
Me too I cant get it to connect to Bitbucket on VS 2017

**Comment by C057A5** [comment] 2018-01-31 17:37
Two machines on Win10 17083, both with latest VisualStudio 2017 (currently 15.5.6). One has the issue, the other not. I built the project on the machine with the issue, but cannot login. I'm not familiar with WPF, but it looks like ShardedDictionary.xaml is not loading with this error:
![image](https://user-images.githubusercontent.com/7055322/35637829-0ec3a020-06be-11e8-8042-5871b29c6d03.png)
TextBoxStyles.xaml shows now error.

**Comment by MistyKuu** [comment] 2018-02-03 11:22
@C057A5 it's Visual Studio designer bug. I wouldn't worry about this.

**Comment by C057A5** [comment] 2018-02-03 22:04
No worries then, but how to make it work on this machine?

**Comment by C057A5** [comment] 2018-02-18 13:28
I tried on a fresh installation of windows 10 + visual studio. Worked for a day, then back to the same behavior: Login doesn't do anything. I suspect any dialog would have the same behavior. ReactiveUI throws an exception inside InitializeComponent of any DialogView, probably because TextBoxStyles doesn't load correctly. This is getting really annoying...

**Comment by C057A5** [comment] 2018-02-20 13:06
Update: There seems to be a conflict between the Bitbucket and the RedGate plugins. It looks like having SQL Prompt causes a WPF version mismatch or something. As soon as I uninstalled SQL Prompt, Bitbucket for VS started working. Didn't need to reboot or anything.

**Comment by dwilkie1** [comment] 2018-02-20 13:46
Ah that checks out. I have redgate installed.

**Comment by C057A5** [comment] 2018-02-28 17:19
In the end, I kept SQL Prompt for SSMS but disabled it in VisualStudio. I was able to login etc. again after a VS restart. Nevertheless, I'd like to have SQL Prompt also in Visual Studio.

**Comment by MistyKuu** [comment] 2018-03-21 21:27
Moving to https://github.com/MistyKuu/bitbucket-for-visual-studio/issues/53

**Closed by MistyKuu** 2018-03-21 21:27 UTC
Labels: bug
