### ISSUE TITLE
The number of changed files shown for a PR seems to be limited to around 300

### ISSUE THREAD

**Issue by DmytroLapshyn** [MistyKuu/bitbucket-for-visual-studio#16] opened 2017-06-15 09:30 UTC
Not sure if this is a limitation of the plugin itself, or that of the BitBucket API, but I've noticed that for really large PRs the number of changed files shown in the plug-in's tool window pane is limited to 300 something. I really understand that's quite a special case that might go completely unnoticed for the majority of the user base, but if that's something that can be rectified with a quick fix, I'd suggest that fix be incorporated into a future release.

**Comment by MistyKuu** [comment] 2017-06-15 10:22
Hey Dmytro,
is this Bitbucket Cloud or Bitbucket server?

**Comment by DmytroLapshyn** [comment] 2017-06-15 10:25
Apologies for leaving this out in the first place - that's BitBucket Server. Is there's something I could do locally to help you identify the potential problem?

**Comment by MistyKuu** [comment] 2017-06-15 10:34
I'm afraid that there is a cap. Look at pull request diff endpoint:
https://developer.atlassian.com/static/rest/bitbucket-server/4.13.0/bitbucket-rest.html#idm45295356631136

And quote:

> Note: This RESTful endpoint is currently not paged. The server will internally apply a hard cap to the streamed lines, and it is not possible to request subsequent pages if that cap is exceeded.

It looks like I'll have to try another way e.g. generate it from commits between branches.

**Comment by DmytroLapshyn** [comment] 2017-06-15 10:44
> It looks like I'll have to try another way e.g. generate it from commits between branches.

Hmm, I would probably be careful here in order to avoid creating an excessive load on the server. Now that you have quoted the hard cap on the API side, I am inclined to think this was introduced for a reason. 

I would probably just say that it was really an edge case of misusing the pull request feature that was prompted this issue in the first place, so on second thought I would "de-prio" it given the new knowledge. But of course it's totally up to you to decide :)

**Comment by MistyKuu** [comment] 2017-07-03 17:03
I started looking at it and I can't reproduce this issue. 
I have 1k files changed, every file has between 1-100 characters added and still I'm getting the entire response. Is there anything specific in your scenario?

![image](https://user-images.githubusercontent.com/10333668/27802156-51ba101e-6022-11e7-97f1-af1a54d994de.png)

**Comment by DmytroLapshyn** [comment] 2017-07-04 16:11
I am unfortunately not aware of any specifics that might be pertinent to the issue in question. I can probably speculate about certain BitBucket configuration settings that might have non-standard values on our on-premises BitBucket server, but then I'd appreciate some hints regarding where to look.

Shall we mark the issue as "Cannot reproduce" for now, and if I have a more robust repro case, I will reply to this thread with more details?

**Comment by MistyKuu** [comment] 2017-07-07 07:20
Yes, let's close it for now. Thanks

**Closed by MistyKuu** 2017-07-07 07:20 UTC
Labels: bug
